### ISSUE TITLE
Prerendering, SEO et crawling google

### ISSUE THREAD

**Issue by raphodn** [quiz-anthropocene/admin-backend#28]
## Objectif

Se pencher sur la question du SEO, c'est une app Vue.js donc les pages ne sont pas statiques

## Détails

Les SPA sont en général mal crawlés et indexées, voir comment améliorer ça
pre-render du frontend ?

## Todo / idées

- [x] ajout du site sur Google Search Console
- [x] se passer du backend et utiliser la donnée stockées dans les fichiers yaml du dossier data
- [x] pre-render certaines pages
- [x] avoir des meta tags dynamiques en fonction des pages (titre, description, image)
- [ ] savoir d'où vient le traffic du site ?
- [ ] être mieux référencé sur les moteurs de recherche
- [ ] loader l'application plus rapidement (chantier à part entière)

## Also

Transformer le frontend en Progressive Web App https://github.com/raphodn/know-your-planet/issues/31

## Meta tags and prerendering

https://metatags.io/

Twitter : https://cards-dev.twitter.com/validator
Facebook : https://developers.facebook.com/tools/debug/
Linkedin : https://www.linkedin.com/post-inspector

https://github.com/nuxt/vue-meta/issues/133

**Comment by raphodn** [comment]
Idées:
- se passer du backend et utiliser la donnée stockées dans les fichiers yaml du dossier `data`
- pre-render certaines pages
- passer sur du static-site generator ?
