### ISSUE TITLE
Feuille de route : Janvier-Avril 2021

### ISSUE THREAD

**Issue by raphodn** [quiz-anthropocene/admin-backend#424]
## Fonctionnalités

- [x] Mettre des quizs en avant. Et choisir lesquels (https://github.com/raphodn/know-your-planet/issues/274)
- [x] Pouvoir ordonner les questions d'un quiz (https://github.com/raphodn/know-your-planet/issues/266)
- [x] Proposer des quizs similaires / suivants à la fin d'un quiz (https://github.com/raphodn/know-your-planet/issues/181)
- [x] Afficher quelques stats à la fin d'un quiz (https://github.com/raphodn/know-your-planet/issues/349)

## UX

- Refonte de la page principale
- [x] Meilleur filtrage / tri des quizs
- [x] Indiquer les questions non validées (https://github.com/raphodn/know-your-planet/issues/237)
- Indiquer la durée estimée d'un quiz (https://github.com/raphodn/know-your-planet/issues/351)
- Nouveau logo
- [x] Afficher les réponses audio & vidéo séparément

## Documentation & ressources

- Afficher la licence (https://github.com/raphodn/know-your-planet/issues/364)
- Ajouter la possibilité de faire des dons (https://github.com/raphodn/know-your-planet/issues/198)
- [x] Afficher le score EcoIndex du site (https://github.com/raphodn/know-your-planet/issues/258)
- [x] Schéma d'architecture de l'application (https://github.com/raphodn/know-your-planet/issues/246)
- [x] Afficher les réseaux sociaux dans le footer (https://github.com/raphodn/know-your-planet/issues/195)

## Autres usages

- [x] Traduire l'interface en anglais (https://github.com/raphodn/know-your-planet/issues/360)
- Pouvoir imprimer des questions sous forme de cartes (https://github.com/raphodn/know-your-planet/issues/201)

## Mai-Août

- PWA
- Avoir des sessions utilisateurs
